# Site
title: 🍬Yobo's Blog🍭
subtitle:
description:
author: Yobo
language:
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://yoursite.com
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# Directory
source_dir: docs
public_dir: docs/.vuepress/dist

# Deployment
deploy:
  type: git
  repo: https://github.com/yoboyoboyobo/yoboyoboyobo.github.io.git
